import { CaretRight, DiscordLogo, FileArrowDown, Image, Lightning } from "phosphor-react";
import { Player, Youtube, DefaultUi } from '@vime/react'

import '@vime/core/themes/default.css'

export default function Video() {
  return(
    <div className="flex-1">
      <div className="bg-black flex justify-center">
        <div className="h-full w-full max-w-[1100px] max-h-[60vh] aspect-video">
          <Player>
            <Youtube videoId="cUT665tW4v8"/>
            <DefaultUi />
          </Player>
        </div>
      </div>

      <div className="p-8 max-w-[1100px] mx-auto ">
        <div className="flex items-start gap-16 ">
          <div className="flex-1">
            <h1 className="text-2xl font-bold">
              Lesson 01 - Project Settings
            </h1>
            <p className="mt-4 text-gray-200 leading-relaxed">
              In this lesson we will start the project by creating the base structure application using ReactJS, Vite and TailwindCSS. We will also setup our project in GraphCMS by creating the application entities and integrating the GraphQL API generated by the platform in our front-end using Apollo Client.
            </p>

            <div className="flex items-center gap-4 mt-8">
              <img 
              className="h-16 w-16 rounded-full border-2 border-blue-500"
              src="https://github.com/diego3g.png" 
              alt="" 
              />

              <div className="leading-relaxed">
                <strong className="font-bold text-2xl block">
                  Diego Fernandes
                </strong>
                <span className="text-gray-200 text-sm block">
                  CTO at Rockeseat
                </span>
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-4">
            <a href="#" className="p-4 text-sm bg-green-500 flex items-center rounded font-bold uppercase gap-2 justify-center hover:bg-green-700 transition-colors">
              <DiscordLogo size={24} />
              Discord Community
            </a>
            <a href="#" className="p-4 text-sm border border-blue-500 text-blue-500 flex items-center rounded font-bold uppercase gap-2 justify-center hover:bg-blue-500 hover:text-gray-900">
              <Lightning size={24} />
              Access Challenge
            </a>
          </div>
        </div>
        <div className="gap-8 mt-10 grid grid-cols-2">
          <a href="" className="bg-gray-700 rounded overflow-hidden flex items-stretch gap-6 hover:bg-gray-600 transition-colors">
            <div className="bg-green-700 h-full p-6 flex items-center">
              <FileArrowDown size={40} />
            </div>
            <div className="py-6 leading-relaxed">
              <strong className="text-2xl">
                Supplementary Material
              </strong>
              <p className="text-sm text-gray-200 mt-2">
                Access supplemental material to accelerate your development
              </p>
            </div>
            <div className="h-full p-6 flex items-center">
              <CaretRight size={24} />
            </div>
          </a>
          <a href="" className="bg-gray-700 rounded overflow-hidden flex items-stretch gap-6 hover:bg-gray-600 transition-colors">
            <div className="bg-green-700 h-full p-6 flex items-center">
              <Image size={40} />
            </div>
            <div className="py-6 leading-relaxed">
              <strong className="text-2xl">
                Exclusive wallpapers
              </strong>
              <p className="text-sm text-gray-200 mt-2">
                Download exclusive Ignite Lab wallpapers and customize your machine
              </p>
            </div>
            <div className="h-full p-6 flex items-center">
              <CaretRight size={24} />
            </div>
          </a>
        </div>
      </div>
    </div>
  )
}